### ISSUE TITLE
节目源失效

### ISSUE THREAD

**Issue by zdzym** [wuwentao/bj-mobile-iptv#1]
![屏幕截图 2021-11-28 151826](https://user-images.githubusercontent.com/41980497/143733458-7cb60f73-3e92-4eb3-a129-6ff95466eaec.jpg)

**Comment by wuwentao** [comment]
最近没顾上看，那就是新换的节目源又挂了……
还得重新更新，我没有开通移动的IPTV，抓不到节目源啊

**Comment by wuwentao** [comment]
论坛去扒了一部分，无效的都干掉了，暂时只能这么着了， 其他源我没法抓，只能慢慢积累吧！
