### ISSUE TITLE
这次的源

### ISSUE THREAD

**Issue by Lsuntiny** [wuwentao/bj-mobile-iptv#2]
这次的源上来就失效了。

**Comment by wuwentao** [comment]
嗯，单播的这种节目源确实的太垃圾了！
北京联通的节目源就是组播地址，相当稳定，几年都不怎么变化！
目前北京移动的IPTV节目源，最佳的解决办法是开通了北京移动IPTV的用户（有机顶盒的）抓包获取节目源，然后更新结果，我这边没开通IPTV，也没办法直接抓包获取节目单！

**Comment by wuwentao** [comment]
论坛去扒了一部分，无效的都干掉了，暂时只能这么着了， 其他源我没法抓，只能慢慢积累吧！

**Comment by Lsuntiny** [comment]
你第一次的源延时低且秒开，我用的是移动网络，联能组播不能用，一直在找移动较好的单播源。这次的源多数打不开，但是还是要谢谢大神！

**Comment by wuwentao** [comment]
节目源昨晚都验证过，都没问题，我猜您应该不是北京移动的网络吧？是其他移动的吧

**Comment by Lsuntiny** [comment]
不是北京移动，是广东移动。

**Comment by wuwentao** [comment]
是的，所以都播不了！
广东没有本地的IPTV么？除非是互联网公共IPTV源，一般还是找本地运营商的更稳妥，北京的肯定不适合您用！
之前的那种都是临时的，类似于互联网公共IPTV源，所以挂的也很快！
不过这个节目源估计也有可能挂，没办法，联通的多播才是最佳的选择，稳定的几年都没啥更新没啥变化的

**Comment by fafactx** [comment]
可以先用陕西，浙江，南京等看着，等我有空给你们抓一套。
