### ISSUE TITLE
北京移动组播地址有木有啊

### ISSUE THREAD

**Issue by EricInBj** [wuwentao/bj-mobile-iptv#4]

**Comment by wuwentao** [comment]
目前没有……
大概是移动没部署吧

**Comment by EricInBj** [comment]
移动不是号称有那种 12 块/月的 "真" IPTV 了吗...

**Comment by wuwentao** [comment]
单播不是也能让你看IPTV么？不影响收费吧？

**Comment by EricInBj** [comment]
不能吧...你是说收了 12 块的, 还是以前魔百盒那个 ott 地址?

光猫上有个专门的 IPTV 口, 光猫里也能看到有个 iptv 的连接了啊.

**Comment by wuwentao** [comment]
那个只是连接通道，和实际服务器在哪没半毛钱关系！
以上github贡献的地址就是有人抓了贡献出来的机顶盒里的地址……
因为地址包含认证信息，所以一般人不会给你贡献出来，这就是为什么移动的IPTV源很少的原因

**Comment by EricInBj** [comment]
他跟联通那个不一样, 联通的 IPTV 连接是 IPOE 的, 无认证. 
北京移动的连接我看也是 PPPOE... 
路由插光猫 IPTV 口上无法获取 IP 地址真正建立连接.
本来是想像联通那样,就算不开通 IPTV 也能白嫖组播数据的...

**Comment by wuwentao** [comment]
谁说联通没有认证的？一样的需要通过认证！
直播走组播不认证而已，你试试点播，回放，还有其他收费资源的查看，都是一样需要认证，单独的用户名和密码，在机顶盒里预配置才行。
移动没有组播，只有单播，认证都是要走单播的，但是这些和认不认证没任何关系，没有组播才是根源，条件不具备。

**Comment by EricInBj** [comment]
恩,我说的就是组播, 联通的没开通 IPTV 也一样可以收组播包的.

移动没组播的话, 就不折腾他了, 老实歌华吧......
